<?php

/**
 * Base class that represents a row from the 'tasks' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 12/12/08 17:42:00
 *
 * @package    lib.model.om
 */
abstract class BaseTasks extends BaseObject  implements Persistent {


  const PEER = 'TasksPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        TasksPeer
	 */
	protected static $peer;

	/**
	 * The value for the taskid field.
	 * @var        int
	 */
	protected $taskid;

	/**
	 * The value for the scdids field.
	 * Note: this column has a database default value of: '0'
	 * @var        string
	 */
	protected $scdids;

	/**
	 * The value for the userid field.
	 * @var        int
	 */
	protected $userid;

	/**
	 * The value for the taskpriority field.
	 * Note: this column has a database default value of: 3
	 * @var        int
	 */
	protected $taskpriority;

	/**
	 * The value for the taskstring field.
	 * @var        string
	 */
	protected $taskstring;

	/**
	 * The value for the taskdesciption field.
	 * @var        string
	 */
	protected $taskdesciption;

	/**
	 * The value for the deleted field.
	 * @var        int
	 */
	protected $deleted;

	/**
	 * The value for the active field.
	 * Note: this column has a database default value of: 1
	 * @var        int
	 */
	protected $active;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseTasks object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->scdids = '0';
		$this->taskpriority = 3;
		$this->active = 1;
	}

	/**
	 * Get the [taskid] column value.
	 * 
	 * @return     int
	 */
	public function getTaskid()
	{
		return $this->taskid;
	}

	/**
	 * Get the [scdids] column value.
	 * 
	 * @return     string
	 */
	public function getScdids()
	{
		return $this->scdids;
	}

	/**
	 * Get the [userid] column value.
	 * 
	 * @return     int
	 */
	public function getUserid()
	{
		return $this->userid;
	}

	/**
	 * Get the [taskpriority] column value.
	 * 
	 * @return     int
	 */
	public function getTaskpriority()
	{
		return $this->taskpriority;
	}

	/**
	 * Get the [taskstring] column value.
	 * 
	 * @return     string
	 */
	public function getTaskstring()
	{
		return $this->taskstring;
	}

	/**
	 * Get the [taskdesciption] column value.
	 * 
	 * @return     string
	 */
	public function getTaskdesciption()
	{
		return $this->taskdesciption;
	}

	/**
	 * Get the [deleted] column value.
	 * 
	 * @return     int
	 */
	public function getDeleted()
	{
		return $this->deleted;
	}

	/**
	 * Get the [active] column value.
	 * 
	 * @return     int
	 */
	public function getActive()
	{
		return $this->active;
	}

	/**
	 * Set the value of [taskid] column.
	 * 
	 * @param      int $v new value
	 * @return     Tasks The current object (for fluent API support)
	 */
	public function setTaskid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->taskid !== $v) {
			$this->taskid = $v;
			$this->modifiedColumns[] = TasksPeer::TASKID;
		}

		return $this;
	} // setTaskid()

	/**
	 * Set the value of [scdids] column.
	 * 
	 * @param      string $v new value
	 * @return     Tasks The current object (for fluent API support)
	 */
	public function setScdids($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->scdids !== $v || $v === '0') {
			$this->scdids = $v;
			$this->modifiedColumns[] = TasksPeer::SCDIDS;
		}

		return $this;
	} // setScdids()

	/**
	 * Set the value of [userid] column.
	 * 
	 * @param      int $v new value
	 * @return     Tasks The current object (for fluent API support)
	 */
	public function setUserid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->userid !== $v) {
			$this->userid = $v;
			$this->modifiedColumns[] = TasksPeer::USERID;
		}

		return $this;
	} // setUserid()

	/**
	 * Set the value of [taskpriority] column.
	 * 
	 * @param      int $v new value
	 * @return     Tasks The current object (for fluent API support)
	 */
	public function setTaskpriority($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->taskpriority !== $v || $v === 3) {
			$this->taskpriority = $v;
			$this->modifiedColumns[] = TasksPeer::TASKPRIORITY;
		}

		return $this;
	} // setTaskpriority()

	/**
	 * Set the value of [taskstring] column.
	 * 
	 * @param      string $v new value
	 * @return     Tasks The current object (for fluent API support)
	 */
	public function setTaskstring($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->taskstring !== $v) {
			$this->taskstring = $v;
			$this->modifiedColumns[] = TasksPeer::TASKSTRING;
		}

		return $this;
	} // setTaskstring()

	/**
	 * Set the value of [taskdesciption] column.
	 * 
	 * @param      string $v new value
	 * @return     Tasks The current object (for fluent API support)
	 */
	public function setTaskdesciption($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->taskdesciption !== $v) {
			$this->taskdesciption = $v;
			$this->modifiedColumns[] = TasksPeer::TASKDESCIPTION;
		}

		return $this;
	} // setTaskdesciption()

	/**
	 * Set the value of [deleted] column.
	 * 
	 * @param      int $v new value
	 * @return     Tasks The current object (for fluent API support)
	 */
	public function setDeleted($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->deleted !== $v) {
			$this->deleted = $v;
			$this->modifiedColumns[] = TasksPeer::DELETED;
		}

		return $this;
	} // setDeleted()

	/**
	 * Set the value of [active] column.
	 * 
	 * @param      int $v new value
	 * @return     Tasks The current object (for fluent API support)
	 */
	public function setActive($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->active !== $v || $v === 1) {
			$this->active = $v;
			$this->modifiedColumns[] = TasksPeer::ACTIVE;
		}

		return $this;
	} // setActive()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(TasksPeer::SCDIDS,TasksPeer::TASKPRIORITY,TasksPeer::ACTIVE))) {
				return false;
			}

			if ($this->scdids !== '0') {
				return false;
			}

			if ($this->taskpriority !== 3) {
				return false;
			}

			if ($this->active !== 1) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->taskid = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->scdids = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->userid = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->taskpriority = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->taskstring = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->taskdesciption = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->deleted = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->active = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 8; // 8 = TasksPeer::NUM_COLUMNS - TasksPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Tasks object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TasksPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = TasksPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTasks:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TasksPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			TasksPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseTasks:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTasks:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TasksPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseTasks:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			TasksPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = TasksPeer::TASKID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = TasksPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setTaskid($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += TasksPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = TasksPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TasksPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getTaskid();
				break;
			case 1:
				return $this->getScdids();
				break;
			case 2:
				return $this->getUserid();
				break;
			case 3:
				return $this->getTaskpriority();
				break;
			case 4:
				return $this->getTaskstring();
				break;
			case 5:
				return $this->getTaskdesciption();
				break;
			case 6:
				return $this->getDeleted();
				break;
			case 7:
				return $this->getActive();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = TasksPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getTaskid(),
			$keys[1] => $this->getScdids(),
			$keys[2] => $this->getUserid(),
			$keys[3] => $this->getTaskpriority(),
			$keys[4] => $this->getTaskstring(),
			$keys[5] => $this->getTaskdesciption(),
			$keys[6] => $this->getDeleted(),
			$keys[7] => $this->getActive(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TasksPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setTaskid($value);
				break;
			case 1:
				$this->setScdids($value);
				break;
			case 2:
				$this->setUserid($value);
				break;
			case 3:
				$this->setTaskpriority($value);
				break;
			case 4:
				$this->setTaskstring($value);
				break;
			case 5:
				$this->setTaskdesciption($value);
				break;
			case 6:
				$this->setDeleted($value);
				break;
			case 7:
				$this->setActive($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = TasksPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setTaskid($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setScdids($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setUserid($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTaskpriority($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setTaskstring($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setTaskdesciption($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setDeleted($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setActive($arr[$keys[7]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(TasksPeer::DATABASE_NAME);

		if ($this->isColumnModified(TasksPeer::TASKID)) $criteria->add(TasksPeer::TASKID, $this->taskid);
		if ($this->isColumnModified(TasksPeer::SCDIDS)) $criteria->add(TasksPeer::SCDIDS, $this->scdids);
		if ($this->isColumnModified(TasksPeer::USERID)) $criteria->add(TasksPeer::USERID, $this->userid);
		if ($this->isColumnModified(TasksPeer::TASKPRIORITY)) $criteria->add(TasksPeer::TASKPRIORITY, $this->taskpriority);
		if ($this->isColumnModified(TasksPeer::TASKSTRING)) $criteria->add(TasksPeer::TASKSTRING, $this->taskstring);
		if ($this->isColumnModified(TasksPeer::TASKDESCIPTION)) $criteria->add(TasksPeer::TASKDESCIPTION, $this->taskdesciption);
		if ($this->isColumnModified(TasksPeer::DELETED)) $criteria->add(TasksPeer::DELETED, $this->deleted);
		if ($this->isColumnModified(TasksPeer::ACTIVE)) $criteria->add(TasksPeer::ACTIVE, $this->active);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(TasksPeer::DATABASE_NAME);

		$criteria->add(TasksPeer::TASKID, $this->taskid);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getTaskid();
	}

	/**
	 * Generic method to set the primary key (taskid column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setTaskid($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Tasks (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setScdids($this->scdids);

		$copyObj->setUserid($this->userid);

		$copyObj->setTaskpriority($this->taskpriority);

		$copyObj->setTaskstring($this->taskstring);

		$copyObj->setTaskdesciption($this->taskdesciption);

		$copyObj->setDeleted($this->deleted);

		$copyObj->setActive($this->active);


		$copyObj->setNew(true);

		$copyObj->setTaskid(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Tasks Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     TasksPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new TasksPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseTasks:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseTasks::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseTasks
