<?php


/**
 * This class adds structure of 'emailschedule' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 12/13/08 09:34:06
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class EmailscheduleMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.EmailscheduleMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(EmailschedulePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(EmailschedulePeer::TABLE_NAME);
		$tMap->setPhpName('Emailschedule');
		$tMap->setClassname('Emailschedule');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('SCDID', 'Scdid', 'INTEGER', true, 10);

		$tMap->addColumn('USERID', 'Userid', 'INTEGER', true, 10);

		$tMap->addColumn('EMAIL', 'Email', 'VARCHAR', true, 100);

		$tMap->addColumn('SCHEDULE', 'Schedule', 'VARCHAR', false, 100);

		$tMap->addColumn('DELETED', 'Deleted', 'TINYINT', false, 1);

		$tMap->addColumn('ACTIVE', 'Active', 'TINYINT', true, 1);

		$tMap->addColumn('CREATIONDATE', 'Creationdate', 'TIMESTAMP', true, null);

		$tMap->addColumn('LASTRUNDATE', 'Lastrundate', 'TIMESTAMP', false, null);

		$tMap->addColumn('TEMPLATEID', 'Templateid', 'VARCHAR', false, 45);

		$tMap->addColumn('SORTSTRING', 'Sortstring', 'VARCHAR', true, 100);

		$tMap->addColumn('SUBJECT', 'Subject', 'VARCHAR', true, 100);

	} // doBuild()

} // EmailscheduleMapBuilder
